#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Remove all submodules and re-initialize them.

Usage:
  clean_submodule
'
[ -z "$NEMD_SRC" ] && echo "Please source premake" && exit 1
git submodule deinit -f "$NEMD_SRC"
git submodule update --init --recursive --checkout
