#! /bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run the submodule binaries.

Usage:
  nemd_module [lmp|alm|anphon] [args]
'
. nemd_func
[ $# -lt 1 ] && error 'Please specify a module binary.'

dir=build
case $1 in
  lmp)
    name=lammps
    export LAMMPS_POTENTIALS=$(python -c "from nemd import envutils; print(envutils.Src().get('potentials', module='lammps'))")
    ;;
  alm|anphon)
    name=alamode
    dir=$dir/$1
    ;;
  *)
    error "Unknown module binary: $1"
  esac

binary=$(python -c "import $name; print($name.__path__[0])")/$dir/$1

shift
set -- $binary "$@"
debug "$@"; "$@"
