#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run coverage analysis and generate report.

Usage:
  nemd_cover
  nemd_cover driver
  nemd_cover workflow test_workflow_test.py
  nemd_cover module cru_test.py osutils_test.py
  nemd_cover run --source=nemd.numbautils -m pytest $NEMD_SRC/test/unit/module/numbautils_test.py
  nemd_cover html
'
. nemd_func
[ -z "$NEMD_SRC" ] && add_pypath $(dirname $(which nemd_func))
[ -z "$NEMD_SRC" ] || for SUB_DIR in 'driver' 'workflow'; do add_pypath $NEMD_SRC/$SUB_DIR/; done
[ ! -z "$NEMD_SRC" ] && export COVERAGE_RCFILE=$NEMD_SRC/test/unit/.coveragerc
[ -z "$PYTEST_ADDOPTS" ] && export PYTEST_ADDOPTS='-m ""'
[ -z "$PLATFORM" ] && export PLATFORM=$(python -c "import platform; print(platform.system().lower())")

[ $# != 0 ] && case $1 in module|driver|workflow) DIRNAME=$1; shift; NUM=$#;; *) { coverage "$@"; exit $?; };; esac

[ -z "$NEMD_SRC" ] && echo "Please source premake" && exit 1
[ ! -z "$DIRNAME" ] && for val in "$@"; do shift; set -- "$@" $NEMD_SRC/test/unit/$DIRNAME/$val; done

for NAME in "workflow" "driver" "module"
  do
    [ ! -z "$DIRNAME" ] && [ "$NAME" != "$DIRNAME" ] && continue
    SOURCE=$NEMD_SRC/$NAME && [ $NAME = "module" ] && SOURCE=$SOURCE/nemd
    [ ! -z "$NUM" ] && [ $NUM != 0 ] || set -- $NEMD_SRC/test/unit/$NAME/*_test.py
    DIR=.coverage_"$NAME"
    coverage run --source=$SOURCE --data-file $DIR/.coverage -m pytest "$@"
    coverage html --data-file=$DIR/.coverage -d $DIR
    open $DIR/index.html
  done
wait