#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run integration tests.

Usage:
  nemd_itest [int int...]
  nemd_itest -dir DIR
  An empty argument runs all tests in $NEMD_SRC/test/integration.
'
set -- nemd_run test_workflow.py "$@"
echo "$@" && "$@"
