#! /bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run the sh & python check.

Usage:
  nemd_check [exist] [args]
'
[ $# -lt 1 ] && echo 'Please specify a check command.' && exit 1

. nemd_func

case $1 in
  exist|cmp|in)
    set -- python -m nemd.test "$@"
    ;;
  *)
    ;;
  esac

debug "$@"; "$@"
