#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run unit tests.

Usage:
  nemd_test [file1 file2...]
  nemd_test -s -v [file1 file2...]
  An empty argument runs all tests inside $NEMD_SRC/test/unit/
'
. nemd_func
[ -z $NEMD_SRC ] && add_pypath $(dirname $(which nemd_func))
[ -z $NEMD_SRC ] || for SUB_DIR in 'driver' 'workflow'; do add_pypath $NEMD_SRC/$SUB_DIR/; done

set -- nemd_run -m pytest "$@"
[ $# != 3 ] && { "$@"; exit $?; }

[ -z "$NEMD_SRC" ] && echo "Please source premake" && exit 1
for SUB_DIR in "module" 'driver' 'workflow'; do
  "$@" $NEMD_SRC/test/unit/$SUB_DIR/*_test.py -n auto
done