#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Functions shared by multiple sh scripts.

Usage:
  . nemd_func
  format_py yapf
  format_py isort

'
# Python
python() { python3.10 "$@"; }

# Debug Printing
[ -z $DEBUG ] && debug() { :; } || debug() { echo "$@"; }

add_path()
{
  [ -z $1 ] && return
  echo $1 && [ -d "$1" ] && echo $PATH | grep -q "$1" && return
  export PATH="$1${PATH:+":$PATH"}"
}

add_pypath()
{
  [ -z $1 ] && return
  echo $1 && [ -d "$1" ] && echo $PYTHONPATH | grep -q "$1" && return
  export PYTHONPATH="$1${PYTHONPATH:+":$PYTHONPATH"}"
}

llvm()
{
  LLVM=$(brew --prefix llvm)/bin
  echo $PATH | grep -q $$LLVM || export PATH="$LLVM${PATH:+":$PATH"}"
}

git_update()
{
  set -- --init "$@"
  [ ! -z $SHALLOW ] && set -- --depth 1 "$@"
  set -- git submodule update "$@"
  "$@"
}

cmake_build()
{
  set -- cmake "$@" -B build
  echo "$@"; "$@"
  cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.logicalcpu)
}

# param $@: input command to format python files
# In git repository, format modified python files tracked and those untracked
# Outside git repository, format python files in $NEMD_SRC (sub-)directories
format_py()
{
  if (2>/dev/null git rev-parse --is-inside-work-tree 1>/dev/null); then
    # In git repository, yapf python files modified and untracked files
    TOPLEVEL=$(git rev-parse --show-toplevel)
    FILES=$(git diff $(git rev-parse --abbrev-ref --symbolic-full-name @{u}) --name-only)
    FILES="$FILES $(git ls-files --others --exclude-standard --full-name $TOPLEVEL)"
    FILES=$(echo $FILES | sed 's/  */\n/g' | grep ".*\.py" | sed "s@[^ ]* *@$TOPLEVEL/&@g")
    for file in $FILES; do [ -f "$file" ] && files="$files $file"; done
    printf "Formatting %15s    %-40s\n" "$(echo "$files" | wc -w) .py files" $TOPLEVEL
    [ -n "$FILES" ] && $@ $files
    return 0
  fi

  # Not in git repository, yapf python files in $NEMD_SRC repository
  [ -z "$NEMD_SRC" ] && echo "Please source premake" && return 1
  for SUB_DIR in "setup.py" "driver" "workflow" "module/nemd" "test" "practice"
  do
    FILES="$(find "$NEMD_SRC/$SUB_DIR" -type f -name "*.py" 2>/dev/null)"
    printf "Formatting %15s    %-40s\n" "$(echo "$FILES" | wc -w) .py files" $NEMD_SRC/$SUB_DIR
    [ -n "$FILES" ] && "$@" $FILES 1>/dev/null &
  done
  wait
  echo "Done!"
  return 0
}

# echo error message to std err and exit 1
error() {
  echo "Error: $1" >&2
  exit 1
  }
