#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run performance tests.

Usage:
  nemd_ptest [int int...]
  nemd_ptest -dir DIR
  An empty argument runs all tests in $NEMD_SRC/test/performance.
'
set -- nemd_run test_workflow.py -name performance "$@"
echo "$@" && "$@"