#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run integration tests.

Usage:
  run_itest [int int...]
  run_itest -dir DIR
  An empty argument runs all tests in $NEMD_SRC/test/integration.
'
set -- nemd_run test_workflow.py "$@"
echo "$@" && "$@"
