#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run unit tests.

Usage:
  run_test [file1 file2...]
  run_test -s -v [file1 file2...]
  An empty argument runs all tests in the $NEMD_SRC/test/unit directory.
'
CMD="nemd_run -m pytest"
if [ $# != 0 ] || [ -z $NEMD_SRC ]; then
  $CMD "$@"
  exit $?
fi

for SUB_DIR in "module" 'driver' 'worflow'; do
    $CMD $NEMD_SRC/test/unit/$SUB_DIR/*_test.py -n auto
done
