#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Set environmental variables, locate the script, and execute the python program.

usage:
  nemd_run mol_bldr_driver.py [Ar] -DEBUG -JOBNAME jobname -PYTHON 1

Set environmental variables from command-line arguments.
  1. -JOBNAME [STR]: jobname based on which output files are named
  2. -PYTHON [INT]: the python mode (e.g., 0: original, 1: compiled)
  3. -DEBUG: debug mode for additional printing and output files
  4. -INTERAC: pop up the interactive GUI

Supported additional flags:
  -m venv|yapf|pytest|cProfile
  -X importtime
  -c <program passed in as string>
'
FLAG_PYTHON="-PYTHON"
FLAG_JOBNAME="-JOBNAME"
FLAG_INTERAC="-INTERAC"
FLAG_SCREEN="-screen"

# Help
[ "$1" = "-h" ] && echo "Example: nemd_run mol_bldr_driver.py [Ar]" && exit 0

# Debug Mode (# -DEBUG -> on)
a=''; for val in "$@" ""; do [ "$a" = "-DEBUG" ] && export DEBUG='1' && break || a=$val; done
# -DEGUG n | no | f | false | off | 0 -> off
[ ! -z $DEBUG ] && case $(echo $val | tr [A-Z] [a-z]) in n|no|f|false|off|0) export DEBUG='' ;; esac
# TQDM off by default
export TQDM_DISABLE='1'

. nemd_func

# Python script
for val in "$@"; do
  shift
  case $val in
    *.py|*.py::*)
      # Python Script
      SCRIPT=${val%%::*} && debug "Python Script: $SCRIPT"
      NAME=$(basename $SCRIPT)
      # Set JOBNAME
      for SUFFIX in _driver.py _workflow.py ".*"; do export JOBNAME=${NAME%%$SUFFIX} && [ $JOBNAME != $NAME ] && break; done
      debug $JOBNAME
      # Absolute (or relative) path or in $PATH
      SPATH="$(cd $(dirname $SCRIPT); pwd)/$NAME" && debug $SPATH
      [ ! -f "$SPATH" ] && SPATH=$(which $SCRIPT) && debug $SPATH
      [ ! -f "$SPATH" ] && echo "Please install $NAME, or source premake" && exit 2
      val=$SPATH${val#$SCRIPT}
      ;;
      esac
  set -- "$@" "$val"
done

# Command-line Arguments
val=''; for nxt in "$@" ''; do
  case $val in
    -*)
      [ -z ${FLAG_PYTHON##$val*} ] && export PYTHON=$nxt
      [ -z ${FLAG_JOBNAME##$val*} ] && export JOBNAME=$nxt
      [ -z ${FLAG_INTERAC##$val*} ] && export INTERAC='1'
      [ -z ${FLAG_SCREEN##$val*} ] && [ $nxt != "off" ] && export TQDM_DISABLE=''
      ;;
    esac
  val=$nxt
done

debug "$@"; python "$@"
