#! /bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run the sh & python check.

Usage:
  nemd_check [exist] [args]
'
. nemd_func
[ $# -lt 1 ] && error 'Please specify a check command.'

set -- python -m nemd.check "$@"
debug "$@"; "$@"
