#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run coverage analysis and generate report.

Usage:
  nemd_cover
  nemd_cover run --source=nemd.numbautils -m pytest $NEMD_SRC/test/unit/module/numbautils_test.py
  nemd_cover html
'
. nemd_func
[ -z $NEMD_SRC ] && add_pypath $(dirname $(which nemd_func))
[ -z $NEMD_SRC ] || for SUB_DIR in 'driver' 'workflow'; do add_pypath $NEMD_SRC/$SUB_DIR/; done

export PYTEST_ADDOPTS='-m ""'
export COVERAGE_RCFILE=$NEMD_SRC/test/unit/.coveragerc

[ $# != 0 ] && { coverage "$@"; exit $?; }

[ -z "$NEMD_SRC" ] && echo "Please source premake" && return 1
for NAME in "module" "driver" "workflow"
  do
    [ $NAME = "module" ] && SUB_DIR=$NAME/nemd || SUB_DIR=$NAME
    set -- coverage run --source=$NEMD_SRC/$SUB_DIR --data-file $NAME -m pytest $NEMD_SRC/test/unit/$NAME/*_test.py
    OUTDIR="$NAME"_out
    "$@" && coverage html --data-file=$NAME -d $OUTDIR && open $OUTDIR/index.html &
  done
wait