#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run scientific tests.

Usage:
  nemd_stest [int int...]
  nemd_stest -dir DIR
  An empty argument runs all tests in $NEMD_SRC/test/scientific.
'
set -- nemd_run test_workflow.py -NAME scientific "$@"
echo "$@" && "$@"
