#! /bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run the submodule binaries.

Usage:
  nemd_module [lmp|alm|anphon] [args]
'
[ $# -lt 1 ] && echo 'Please specify a module binary.' && exit 1

. nemd_func

dir=build
case $1 in
  lmp)
    name=lammps
    export LAMMPS_POTENTIALS=$(python -c "from nemd import envutils; print(envutils.get_data('potentials', module='lammps'))")
    ;;
  alm|anphon)
    name=alamode
    dir=$dir/$1
    ;;
  *)
    echo "Unknown module binary: $1" && exit 1
  esac
echo $LAMMPS_POTENTIALS
binary=$(python -c "import $name; print($name.__path__[0])")/$dir/$1
shift
set -- $binary "$@"
debug "$@"; "$@"
