#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Run scientific tests.

Usage:
  run_stest [int int...]
  run_stest -dir DIR
  An empty argument runs all tests in $NEMD_SRC/test/scientific.
'
set -- run_nemd test_workflow.py -name scientific "$@"
echo "$@" && "$@"
