#!/bin/sh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Create a virtual environment and print instructions to activate it.

Usage:
  run_venv ENV_DIR
  An empty argument sets venv as the ENV_DIR.
'
for a in $@;
do
  [ ! -z $skip ] && skip='' && continue;
  [ $a = '--prompt' ] && skip=1 && continue;
  [ $a = ${a#-} ] && ENV_DIR=$a;
done

[ -z $ENV_DIR ] && ENV_DIR=venv && set -- $ENV_DIR $@
set -- run_nemd -m venv $@
echo "$@" && $@
echo "To Activate  : . $ENV_DIR/bin/activate"
echo "To Deactivate: deactivate"