# -*- coding: utf-8 -*-
"""01_tensor_device.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Tf8DYUTZf-W0aCHZhkWBLpUKlZ_7s9z
"""

import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
random_tensor_D

#!nvidia-smi

import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.cuda.device_count()

tensor = torch.tensor([1, 2, 3], device='cpu')
print(tensor, tensor.device)

tensor = torch.tensor([1, 2, 3], device=device)
print(tensor, tensor.device)

# TypeError: can't convert cuda:0 device type tensor to numpy.
# tensor.numpy()
tensor.cpu().numpy()
