#!/bin/zsh
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Install virtual machine, download  macOS pgk, and conver it into.iso.
'
brew install --cask virtualbox
git clone https://github.com/corpnewt/gibMacOS
python3 gibMacOS.py -v Sonoma
xar -xf "$(find . -name InstallAssistant.pkg)"
hdiutil makehybrid -iso -joliet -o macos.iso *.dmg
