#!/bin/bash
# Under the BSD 3-Clause License by Teng Zhang (zhteg4@gmail.com)
: '
Setup MacBook (Sonoma 14.5) and Ubuntu (22.04 LTS) ready for nemd pip install.
'
# Version, Packages, and Environment
case $OSTYPE in
  darwin*)
    echo "MacOS not supported."
    ;;
  linux*)
    lsb_release -sr  # 22.04
    sudo apt-get install -y gh git vim python3-pip
    # pip uses --user automatically if not root
    BIN=$(python3 -m site --user-base)/bin
    [ ! -d $BIN ] && mkdir -p $BIN
    echo $PATH | grep -q -v $BIN && export PATH="$BIN${PATH:+":$PATH"}"
    ;;
esac

# Git
if [ -z $(git config user.name) ]; then
  git config --global core.editor "vim"
  git config --global user.email $(whoami)@gmail.com
  git config --global user.name $(whoami)
fi
if [ ! -d ~/git/nemd ]; then
  gh auth login --hostname GitHub.com --web
  gh auth setup-git
  gh repo clone zhteg4pvt/nemd ~/git/nemd
fi

# Drivers
[[ $OSTYPE != linux* ]] && exit 0
# NVIDIA GPU: * NVIDIA Corporation GP104 [GeForce GTX 1080] *
(lspci | grep VGA | grep -q -v NVIDIA) && echo 'No NVIDIA GPU found.' && exit 0
sudo ubuntu-drivers --gpgpu install
sudo apt upgrade -y
read -p "Driver installed. Reboot? [y/n]? " answer
case "$answer" in Y|y) echo "rebooting..."; reboot ;; *) ;; esac
echo "no reboot. (GPU driver may not be working)"
